# Generated by Django 5.1 on 2024-08-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=7)),
                ('seats', models.IntegerField()),
                ('transmission', models.CharField(choices=[('AT', 'Automatic'), ('MT', 'Manual')], max_length=10)),
                ('fuel_type', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('gearbox', models.CharField(choices=[('AUTO', 'Automatic'), ('MAN', 'Manual')], max_length=10)),
                ('mileage', models.CharField(max_length=20)),
            ],
        ),
    ]
